# Uncomment the next line to define a global platform for your project
 platform :macos, '10.13'

target 'Six' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Six
  pod 'Sparkle', '~> 1.24.0'
  pod 'Moya', '~> 13.0.0'
  pod 'Kingfisher', '~> 5.15.5'
  pod 'FRadioPlayer'
#  pod 'RealmSwift'
  pod 'TSAppKit'
end
